### ISSUE TITLE
Give credits to @6nz

### ISSUE THREAD

**Issue by wnelson03** [Lawxsz/bypass-virus-total#1]
The code is from https://github.com/6nz/python-anti-debugger

Please give @6nz credits

**Comment by 6nz** [comment]
+ the list is from https://github.com/6nz/virustotal-vm-blacklist

**Comment by Lawxsz** [comment]
> The code is from https://github.com/6nz/python-anti-debugger
> 
> Please give @6nz credits

Sure! the list of IPs, HWID, mac is from 6nz. (and I also add some lists, now I will add it to the credits!)
